### PR TITLE
Fix boolean comparison when setting primary node

### LINKED ISSUE #41: Boolean comparison fails because of case
@msiegen I just attempted to create a VPS in SCL and encountered the same issue you did when creating the MSP VPS last night.

What was the fix to work around these errors? It sounds like there's a bug in `make-vps`

```
root@g1-n01:~# /root/bin/make-vps.sh -n $newvpsname -s $numberofslices -o $os
INFO: SSH Key OK: nbs@sonic.net
INFO: Creating vps
Instance name: tuxpaint.org
Shares: 1
  * Ram 1G
  * Disk 25G
Target IP: 216.252.162.212
Target vlan: virbr3005
Target netmask: 255.255.255.192 (/26)
Target gateway: 216.252.162.254
Target OS: debootstrap+focal
Failure: prerequisites not met for this operation:
error type: unknown_entity, error details:
Instance name tuxpaint.org not found
ssh: Could not resolve hostname : Name or service not known
Unable to reach  via SSH
```

Running with `set -x` I see

```
++ gnt-instance list --no-headers -o pnode tuxpaint.org
Failure: prerequisites not met for this operation:
error type: unknown_entity, error details:
Instance name tuxpaint.org not found
```

which is because earlier, it fails to set a primary node because of this

```
++ json_read /etc/make-vps.json balance_on_free_space
+ [[ True = \t\r\u\e ]]
```

And this is caused by a bug in the code (not sure how this was never noticed or fixed).

The code is looking for `true` which is how JSON writes the boolean, but the `json_read` isn't outputting JSON, it's outputting a Python variable and Python boolean is `True`

I'll PR a fix

### PR DESCRIPTION
**Pull request by gene1wood**
Fixes #41

### CODE REVIEW

File: bin/make-vps.sh [hunk 1]
```diff
@@ -122,7 +122,8 @@ if [[ -z "${ostype}" ]] ; then
   exit 1
 fi
 
-if [[ "$(json_read /etc/make-vps.json balance_on_free_space)" = "true" ]] ; then
+# The value compared here is "True" not "true" because this is a Python variable not JSON
+if [[ "$(json_read /etc/make-vps.json balance_on_free_space)" = "True" ]] ; then
```
Comment (SuperQ) [inline bin/make-vps.sh:126]:
```suggestion
if [[ "$(json_read /etc/make-vps.json balance_on_free_space | tr '[:upper:]' '[:lower:]')" = "true" ]] ; then
```

**Comment by gene1wood** [comment]
I've deployed this.
